language: android
jdk: oraclejdk8
sudo: required

android:
    components:
        - tools
        - platform-tools
        - android-27
        - build-tools-26.0.2
    
        - exra-android-m2repository
        - extra-google-m2repository

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

script:
    - ./gradlew build

branches:
    only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
